---
title: "US city open crime data availability"
output: github_document
---

This file gives the status of open crime data in the [50 largest US cities by
population](https://en.wikipedia.org/wiki/List_of_United_States_cities_by_population) 
as of June 2018. Cities are listed in descending order of population.

City data are suitable for including in CODE if at least four years of data
are available on all crimes.

This list was last updated in February 2019.

```{r}
library(tidyverse)
```


```{r}
tribble(
  ~City, ~Status, ~Availability,
  "New York, NY", "included", "Data are available and included in CODE",
  "Los Angeles, CA", "included", "Data are available and included in CODE",
  "Chicago, IL", "included", "Data are available and included in CODE",
  "Houston, TX", "unavailable", "No open crime data are available. There is a recent incidents dataset but it only covers calls for service over the past month",
  "Phoenix, AZ", "unavailable", "Only [Part 1 data from November 2015](https://phoenixopendata.com/dataset/crime-data) are available",
  "Philadelphia, PA", "problem", "Data are [available from 2006 onwards](https://www.opendataphilly.org/dataset/crime-incidents) and appear to include [a code that can be used to match crime types](http://metadata.phila.gov/#home/datasetdetails/5543868920583086178c4f8e/representationdetails/570e7621c03327dc14f4b68d/). However, there is only a dispatch time and no offence time",
  "San Antonio, TX", "unavailable", "No open crime data are available. There is a [San Antonio PD Open Data Initiative](http://www.sanantonio.gov/SAPD/SAPD-Open-Data-Initiative), but it only relates to officer data (e.g. use of force)",
  "San Diego, CA", "unavailable", "No open crime data are available. [CFS data are available](https://data.sandiego.gov/datasets/police-calls-for-service/), but aren't translatable to crimes",
  "Dallas, TX", "unavailable", "Crime data are [available from June 2014 onwards](https://www.dallasopendata.com/Public-Safety/Police-Incidents/tbnj-w5hb) and appear to include categories that could be matched to the CODE categories but exclude all incidents involving juveniles",
  "San Jose, CA", "unavailable", "No open crime data are available (calls for service are available)",
  "Austin, TX", "included", "Data are available and included in CODE",
  "Jacksonville, FL", "unavailable", "No open crime data are available",
  "San Francisco, CA", "included", "Data are available and included in CODE",
  "Columbus, OH", "unavailable", "No open crime data are available",
  "Fort Worth, TX", "included", "Data are available and included in CODE",
  "Indianapolis, IN", "unavailable", "Data are only available for UCR Part 1 crimes",
  "Charlotte, NC", "unavailable", "No open crime data are available",
  "Seattle, WA", "problem", "Data [appear to be available until part-way through 2019](https://data.seattle.gov/Public-Safety/Crime-Data/4fs7-3vj5) but will require manual categorisation",
  "Denver, CO", "problem", "Data are [available for the previous five years](https://www.denvergov.org/opendata/dataset/city-and-county-of-denver-crime). However, 'crimes which by their nature involve juveniles, or which the reports indicate involve juveniles as victims, suspects, or witnesses, are not reported at all.'",
  "Washington, DC", "unavailable", "UCR Part 1 only",
  "Boston, MA", "possible", "Data are [available from August 2015 onwards](https://data.boston.gov/dataset/crime-incident-reports-august-2015-to-date-source-new-system/resource/12cb3883-56f5-47de-afa5-3b1cf61b257b) with fields that could be used to create CODE categories. A previous dataset is available back to 2012, but there is a problem in that a higher proportion of offenses have missing locations in the first six months of 2015, so the data can't be used to produce a continuous time series. **This should be investigated further.**",
  "El Paso, TX", "unavailable", "No open crime data are available",
  "Detroit, MI", "included", "Data are available and included in CODE",
  "Nashville, TN", "possible", "Data [appear to be available in annual files](https://data.nashville.gov/Police/Metro-Nashville-Police-Department-Incidents-2013-/hsz5-g34u) with NIBRS codes from 2013 onwards",
  "Memphis, TN", "possible", "Data appear to be [available from 2006 onwards](https://memphisinternal.data.socrata.com/Public-Safety/Memphis-Police-Department-Public-Safety-Incidents/ybsi-jur4) but will require manual categorisation",
  "Portland, OR", "problem", "Data are [available back to at least 2015](https://www.portlandoregon.gov/police/71978) but are *slightly* difficult to download due to being run on Tableau Public. A substantial minority of cases have neither co-ordinates nor addresses. **This should be investigated further**.",
  "Oklahoma City, OK", "unavailable", "No open crime data are available",
  "Las Vegas, NV", "unavailable", "[UCR Part 1](https://opendata.lasvegasnevada.gov/API-Integration-/Las-Vegas-Metropolitan-Police-calls-for-service/mapc-ixca) only",
  "Louisville, KY", "included", "Data are available and included in CODE",
  "Baltimore, MD", "unavailable", "[UCR Part 1 only](https://data.baltimorecity.gov/Public-Safety/BPD-Part-1-Victim-Based-Crime-Data/wsfq-mvij)",
  "Milwaukee, WI", "unavailable", "Data are [available from 2005 onwards](https://data.milwaukee.gov/dataset/wibr/resource/87843297-a6fa-46d4-ba5d-cb342fb2d3bb) but only for UCR Part 1 crimes",
  "Albuquerque, NM", "unavailable", "Data are [available](https://www.cabq.gov/abq-data) but only for rolling 180 days.",
  "Tucson, AZ", "included", "Data are available and included in CODE",
  "Fresno, CA", "unavailable", "No open crime data are available",
  "Sacramento, CA", "problem", "Open [data are available](http://data.cityofsacramento.org/datasets?page=2&sort=name&t=Public%20Safety), but only for the most-recent two years and without addresses or co-ordinates",
  "Mesa, AZ", "possible", "Data are [available from 2016 onwards](https://data.mesaaz.gov/Public-Safety/Police-Incidents/39rt-2rfj) but without time of day",
  "Kansas City, MO", "included", "Data are available and included in CODE",
  "Atlanta, GA", "unavailable", "Only UCR Part 1 data are available",
  "Long Beach, CA", "unavailable", "No open crime data are available",
  "Omaha, NE", "unavailable", "No open crime data are available",
  "Raleigh, NC", "problem", "Data are available [from 2005 to May 2014](http://data-ral.opendata.arcgis.com/datasets/raleigh-police-incidents-srs?geometry=-78.67%2C35.78%2C-78.616%2C35.792) and [from June 2014 onwards](http://data-ral.opendata.arcgis.com/datasets/24c0b37fa9bb4e16ba8bcaa7e806c615_0). The former dataset has categories that can be converted to CODE categories and the later has NIBRS codes. However, the data are released under [a non-open license](http://data-ral.opendata.arcgis.com/datasets/24c0b37fa9bb4e16ba8bcaa7e806c615_0)",
  "Colorado Springs, CO", "unavailable", "No open crime data are available",
  "Miami, FL", "unavailable", "No open crime data are available",
  "Virginia Beach, VA", "included", "Data are available and included in CODE",
  "Oakland, CA", "problem", "Data are [available but only for 2012, 2013 and 2015](https://data.oaklandnet.com/browse?category=Public+Safety&limitTo=datasets&sortBy=alpha&utf8=✓&page=2)",
  "Minneapolis, MN", "unavailable", "Data are [available from 2010 onwards](http://opendata.minneapolismn.gov/datasets?page=2&sort=name&t=public%20safety), but may refer only to UCR Part 1 crimes",
  "Tulsa, OK", "problem", "Data are [available, but for the rolling previous two years](http://gis-cityoftulsa.opendata.arcgis.com/search?tags=Public%20Safety)",
  "Arlington, TX", "unavailable", "No open crime data are available, but the open data portal says that a 'Public Safety' section is under construction",
  "New Orleans, LA", "problem", "Data are available but some records a duplicated many times, and the staff at the open data portal didn't know why",
  "Wichita, KS", "unavailable", "Data are [available, but only for the most recent 90 days](http://opendata.wichita.gov/datasets/wichita-crime-incidents/data)"
) %>% 
  mutate(Num = row_number()) %>% 
  select(Num, City, Status, Availability) %>% 
  arrange(City) %>% 
  filter(Status == "possible") %>% 
  knitr::kable()
```




